version: '2.4'

networks: 
    fabric-ca:
    
services: 
    ca-root:
        container_name: ca-root
        image: hyperledger/fabric-ca:1.4.3
        environment: 
            - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
            - ROOT_HOST=ca-root
            - ROOT_PORT=7054
            - ROOT_USERNAME=admin
            - ROOT_PASSWORD=adminpw
        volumes: 
            - ./state/ca-root:/etc/hyperledger/fabric-ca-server
            - ./script:/script
        command: sh /script/start-root.sh
        ports: 
            - 7054:7054
        networks: 
            - fabric-ca
    ca-intermediate:
        container_name: ca-intermediate
        image: hyperledger/fabric-ca:1.4.3
        environment: 
            - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
            - ROOT_HOST=ca-root
            - ROOT_PORT=7054
            - ROOT_USERNAME=admin
            - ROOT_PASSWORD=adminpw
            - INTERMEDIATE_HOST=ca-intermediate
            - INTERMEDIATE_PORT=7054
            - INTERMEDIATE_USERNAME=admin
            - INTERMEDIATE_PASSWORD=adminpw
        volumes: 
            - ./state/ca-intermediate:/etc/hyperledger/fabric-ca-server
            - ./state/ca-root:/etc/hyperledger/fabric-ca-server-root
            - ./script:/script
        command: sh /script/start-intermediate.sh
        ports: 
            - 8054:7054
        networks: 
            - fabric-ca
        depends_on: 
            - ca-root
    ca-client:
        container_name: ca-client
        image: hyperledger/fabric-ca-tools:1.2.1
        environment: 
            - FABRIC_CA_SERVER_HOME=/et/hyperledger/fabric-ca-client
            - ROOT_HOST=ca-root
            - ROOT_PORT=7054
            - ROOT_USERNAME=admin
            - ROOT_PASSWORD=adminpw
            - INTERMEDIATE_HOST=ca-intermediate
            - INTERMEDIATE_PORT=7054
            - INTERMEDIATE_USERNAME=admin
            - INTERMEDIATE_PASSWORD=adminpw
        volumes: 
            - ./state/ca-intermediate:/etc/hyperledger/fabric-ca-intermediate
            - ./state/ca-root:/etc/hyperledger/fabric-ca-server-root
            - ./state/ca-client:/etc/hyperledger
            - ./script:/script
        command:  sleep infinity
        networks: 
            - fabric-ca
        depends_on: 
            - ca-root
            - ca-intermediate




